-- MySQL Script generated by MySQL Workbench
-- Tue May 10 19:27:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cs340_sevierk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `dates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dates` ;

CREATE TABLE IF NOT EXISTS `dates` (
  `date` DATETIME NOT NULL,
  `day_of_week` VARCHAR(45) NOT NULL,
  `holiday` TINYINT NOT NULL,
  `weather` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`date`),
  UNIQUE INDEX `date_UNIQUE` (`date` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guests` ;

CREATE TABLE IF NOT EXISTS `guests` (
  `guest_id` INT NOT NULL AUTO_INCREMENT,
  `guest_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone_num` INT NULL DEFAULT NULL,
  UNIQUE INDEX `guest_id_UNIQUE` (`guest_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  PRIMARY KEY (`guest_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orders` ;

CREATE TABLE IF NOT EXISTS `orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `season_pass_holder` TINYINT NOT NULL,
  `guest_id` INT NULL,
  `date` DATETIME NOT NULL,
  `ticket` INT NOT NULL,
  INDEX `fk_orders_date1_idx` (`date` ASC) VISIBLE,
  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC) VISIBLE,
  INDEX `fk_orders_guests` (`guest_id` ASC) VISIBLE,
  PRIMARY KEY (`order_id`),
  CONSTRAINT `fk_orders_guests`
    FOREIGN KEY (`guest_id`)
    REFERENCES `guests` (`guest_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_date1`
    FOREIGN KEY (`date`)
    REFERENCES `dates` (`date`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attractions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `attractions` ;

CREATE TABLE IF NOT EXISTS `attractions` (
  `ride_id` INT NOT NULL,
  `num_riders` INT NOT NULL,
  `date_created` DATETIME NOT NULL,
  `ride_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ride_id`),
  INDEX `fk_attractions_date1_idx` (`date_created` ASC) VISIBLE,
  UNIQUE INDEX `ride_ID_UNIQUE` (`ride_id` ASC) VISIBLE,
  CONSTRAINT `fk_attractions_date1`
    FOREIGN KEY (`date_created`)
    REFERENCES `dates` (`date`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `master_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `master_table` ;

CREATE TABLE IF NOT EXISTS `master_table` (
  `total_guests` INT NOT NULL AUTO_INCREMENT,
  `total_riders` INT NULL DEFAULT NULL,
  `date` DATETIME NOT NULL,
  INDEX `fk_master_table_date1_idx` (`date` ASC) VISIBLE,
  PRIMARY KEY (`total_guests`),
  CONSTRAINT `fk_master_table_date1`
    FOREIGN KEY (`date`)
    REFERENCES `dates` (`date`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guests_has_attractions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guests_has_attractions` ;

CREATE TABLE IF NOT EXISTS `guests_has_attractions` (
  `guest_id` INT NOT NULL,
  `ride_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  INDEX `fk_guests_has_attractions_attractions1_idx` (`ride_id` ASC) VISIBLE,
  INDEX `fk_guests_has_attractions_guests1_idx` (`guest_id` ASC) VISIBLE,
  INDEX `fk_date_idx` (`date` ASC) VISIBLE,
  INDEX `fk_guests_has_attractions_attractions1` (`ride_id` ASC) VISIBLE,
  CONSTRAINT `fk_guests_has_attractions_guests1`
    FOREIGN KEY (`guest_id`)
    REFERENCES `guests` (`guest_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_guests_has_attractions_attractions1`
    FOREIGN KEY (`ride_id`)
    REFERENCES `attractions` (`ride_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_date`
    FOREIGN KEY (`date`)
    REFERENCES `dates` (`date`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Data for table `dates`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `dates` (`date`, `day_of_week`, `holiday`, `weather`) VALUES ('2022-04-22', 'Friday', FALSE, 'Rain');
INSERT INTO `dates` (`date`, `day_of_week`, `holiday`, `weather`) VALUES ('2022-04-23', 'Saturday', FALSE, 'Sunny');
INSERT INTO `dates` (`date`, `day_of_week`, `holiday`, `weather`) VALUES ('2022-04-24', 'SUNDAY', TRUE, 'Cloudy');
        
-- -----------------------------------------------------
-- Data for table `guests`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `guests` (`guest_id`, `guest_name`, `email`, `phone_num`) VALUES (15, 'Joe Smith', 'joesmith@gmail.com', 1111111);
INSERT INTO `guests` (`guest_id`, `guest_name`, `email`, `phone_num`) VALUES (16, 'John Doe', 'johndoe@gmail.com', 999999);
INSERT INTO `guests` (`guest_id`, `guest_name`, `email`, `phone_num`) VALUES (17, 'Nancy Sue', 'NancySue@hotmail.com', NULL);

-- -----------------------------------------------------
-- Data for table `attractions`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `attractions` (`ride_id`, `num_riders`, `date_created`, `ride_name`)
VALUES (2, 
		6, 
		(SELECT date FROM dates WHERE date='2022-04-22 00:00:00'), 
        'Medusa');
        
INSERT INTO `attractions` (`ride_id`, `num_riders`, `date_created`, `ride_name`)
VALUES (3, 
		6, 
		(SELECT date FROM dates WHERE date='2022-04-22 00:00:00'), 
        'Scrambler');
        
INSERT INTO `attractions` (`ride_id`, `num_riders`, `date_created`, `ride_name`)
VALUES (4, 
		6, 
		(SELECT date FROM dates WHERE date='2022-04-22 00:00:00'), 
        'Merry-Go-Round');
        
-- -----------------------------------------------------
-- Data for table `master_table`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `master_table` (`total_guests`, `total_riders`, `date`)
VALUES (156, 
		32, 
        (SELECT date FROM dates WHERE date='2022-04-23'));
        
INSERT INTO `master_table` (`total_guests`, `total_riders`, `date`)
VALUES (213, 
		45, 
        (SELECT date FROM dates WHERE date='2022-04-24'));
        
INSERT INTO `master_table` (`total_guests`, `total_riders`, `date`)
VALUES (98, 
		22, 
        (SELECT date FROM dates WHERE date='2022-04-22'));


-- -----------------------------------------------------
-- Data for table `orders`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `orders` (`order_id`, `season_pass_holder`, `guest_id`, `date`, `ticket`)
VALUES (72, 
		FALSE, 
        (SELECT guest_id FROM guests WHERE guest_id=15), 
        (SELECT date FROM dates WHERE date='2022-04-22 00:00:00'), 
        TRUE);

INSERT INTO `orders` (`order_id`, `season_pass_holder`, `guest_id`, `date`, `ticket`)
VALUES (73, 
		FALSE, 
        (SELECT guest_id FROM guests WHERE guest_id=16), 
        (SELECT date FROM dates WHERE date='2022-04-22 00:00:00'), 
        TRUE);
        
INSERT INTO `orders` (`order_id`, `season_pass_holder`, `guest_id`, `date`, `ticket`)
VALUES (74, 
		TRUE, 
        (SELECT guest_id FROM guests WHERE guest_id=15), 
        (SELECT date FROM dates WHERE date='2022-04-22 00:00:00'), 
        TRUE);

-- -----------------------------------------------------
-- Data for table `guests_has_attractions`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `guests_has_attractions` (`guest_id`, `ride_id`, `date`)
VALUES ((SELECT guest_id FROM guests where guest_id = 15),
        (SELECT ride_id FROM attractions WHERE ride_id = 2), 
        (SELECT date FROM dates WHERE date='2022-04-23'));
        
INSERT INTO `guests_has_attractions` (`guest_id`, `ride_id`, `date`)
VALUES ((SELECT guest_id FROM guests where guest_id = 15),
        (SELECT ride_id FROM attractions WHERE ride_id = 2), 
        (SELECT date FROM dates WHERE date='2022-04-23'));

INSERT INTO `guests_has_attractions` (`guest_id`, `ride_id`, `date`)
VALUES ((SELECT guest_id FROM guests where guest_id = 15),
        (SELECT ride_id FROM attractions WHERE ride_id = 3), 
        (SELECT date FROM dates WHERE date='2022-04-23'));

INSERT INTO `guests_has_attractions` (`guest_id`, `ride_id`, `date`)
VALUES ((SELECT guest_id FROM guests where guest_id = 17),
        (SELECT ride_id FROM attractions WHERE ride_id = 4), 
        (SELECT date FROM dates WHERE date='2022-04-22'));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
